global using System;
global using Microsoft.Maui;
global using Microsoft.Maui.Controls;
global using Microsoft.Maui.Hosting;
global using Microsoft.Maui.Controls.Hosting;
global using Blazor.FlexGrid;
global using Microsoft.Extensions.DependencyInjection;
global using NethereumExplorer.Services;
global using NethereumExplorer.ViewModels;